### ISSUE TITLE
CRM Connection using Office 365 missing crm3.dynamics.com

### ISSUE THREAD

**Issue by mbharodia** [xairrick/CrmCodeGenerator#4]
I have Dynamics 365 Sales and its connection include orgname.crm3.dyanamics.com. I am not able to find relevant server name in the drop down menu. I am not sure whether I am missing anything. Thanks in advance for your help.

**Comment by xairrick** [comment]
thanks for reporting this.   I'll try to get a new build out today.

**Comment by xairrick** [comment]
This is fixed in the latest build

**Comment by mbharodia** [comment]
Thanks a lot for your help!
